// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mymvcapp.Models;

public partial class Pizza
{
    public string Pizzaid { get; set; }

    public string Pizzaname { get; set; }

    public string Description { get; set; }

    public int? Price { get; set; }

    public string Pimage { get; set; }
}