// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace mymvcapp.Models;

public partial class Registration
{
    [Required(ErrorMessage ="please enter username")]
    public string Uname { get; set; }
    [Required(ErrorMessage = "please enter password")]
    public string Password { get; set; }

    public bool? Gender { get; set; }

    public DateTime? Dob { get; set; }
    [Required(ErrorMessage = "please enter valid email")]
    public string Email { get; set; }
   
    [StringLength(10,ErrorMessage ="give 10 digit mobile number")]
    [RegularExpression("[0-9]+",ErrorMessage ="Only numbers are allowed")]
    public string Phone { get; set; }
}